spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 142556
    timeout: 1000
    jedis:
      pool:
        max-idle: 5
        max-active: 10
        max-wait: 2000
        min-idle: 10
  cache:
    cache-names: redisCache
    type: redis
    redis:
      use-key-prefix: false
      time-to-live: 600000
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/chapter7
    username: root
    password: 10142556
    tomcat:
      max-idle: 10
      max-active: 50
      max-wait: 10000
      initial-size: 5
      default-transaction-isolation: 2
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.springboot.chapter7.pojo
logging:
  level:
    root: debug
    org:
      springframework: debug
      org:
        mybatis: debug