spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chapter6
    username: root
    password: 10142556
    tomcat:
      max-idle: 10
      max-active: 50
      max-wait: 1000
      initial-size: 5
      default-transaction-isolation: 2
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: debug
    org:
      springframework: debug
      org:
        mybatis: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.springboot.chapter6.pojo